from config_files import cfg

# SIDE PANELS
SIDE_PANEL_WIDTH = 24 # max(24,round(cfg.SCREEN_WIDTH/3))
SIDE_PANEL_HEIGHT = round(cfg.SCREEN_HEIGHT // 3) # TODO separate by different panels as required

# BOTTOM PANELS
STATUS_BAR_HEIGHT = 3
BOTTOM_PANEL_HEIGHT = round(cfg.SCREEN_HEIGHT // 3) #max(24,round(cfg.SCREEN_HEIGHT/3))
BOTTOM_PANEL_WIDTH = cfg.SCREEN_WIDTH - SIDE_PANEL_WIDTH

# MAP SCREEN
MAP_SCREEN_WIDTH = cfg.SCREEN_WIDTH - SIDE_PANEL_WIDTH
MAP_SCREEN_HEIGHT = cfg.SCREEN_HEIGHT - BOTTOM_PANEL_HEIGHT# - STATUS_BAR_HEIGHT

# PANEL POSITIONS
SIDE_PANEL_X = cfg.SCREEN_WIDTH - SIDE_PANEL_WIDTH
STATUS_BAR_Y = MAP_SCREEN_HEIGHT- STATUS_BAR_HEIGHT
#BOTTOM_PANEL_Y = STATUS_BAR_Y + STATUS_BAR_HEIGHT
BOTTOM_PANEL_Y = MAP_SCREEN_HEIGHT

# PLAYER PANEL
PLAYER_PANEL_HEIGHT = SIDE_PANEL_HEIGHT - 4

# COMBAT PANEL (Enemy list & enemy details)
COMBAT_PANEL_HEIGHT = SIDE_PANEL_HEIGHT + 4

# OBJECTS PANEL
OBJECT_PANEL_HEIGHT = SIDE_PANEL_HEIGHT

# Message panels
MSG_PANEL1_WIDTH = BOTTOM_PANEL_WIDTH // 2
MSG_PANEL2_WIDTH = BOTTOM_PANEL_WIDTH // 2
MSG_PANEL1_X = 0
MSG_PANEL2_X = MSG_PANEL1_WIDTH

# Message display
MSG_X = 1
MSG_HEIGHT = BOTTOM_PANEL_HEIGHT - 3

# POPUP WINDOWS
# INVENTORY_WIDTH = 30