from config_files import cfg

# TODO Map should be 2/3 of screen width & height, panels cover rest

# SIDE PANELS
SIDE_PANEL_WIDTH = 20 
SIDE_PANEL_HEIGHT = round(cfg.SCREEN_HEIGHT // 3)

# BOTTOM PANELS
STATUS_BAR_HEIGHT = 3
BOTTOM_PANEL_HEIGHT = 20 + STATUS_BAR_HEIGHT
BOTTOM_PANEL_WIDTH = cfg.SCREEN_WIDTH - SIDE_PANEL_WIDTH

# MAP SCREEN
MAP_SCREEN_WIDTH = cfg.SCREEN_WIDTH - SIDE_PANEL_WIDTH
MAP_SCREEN_HEIGHT = cfg.SCREEN_HEIGHT - BOTTOM_PANEL_HEIGHT

# PANEL POSITIONS
SIDE_PANEL_X = cfg.SCREEN_WIDTH - SIDE_PANEL_WIDTH
STATUS_BAR_Y = MAP_SCREEN_HEIGHT
BOTTOM_PANEL_Y = STATUS_BAR_Y + STATUS_BAR_HEIGHT

# PLAYER PANEL
# PLAYER_PANEL_WIDTH = 20
# PLAYER_PANEL_HEIGHT = round(SCREEN_HEIGHT // 3)

# COMBAT PANEL (Enemy list & enemy details)
# COMBAT_PANEL_WIDTH = SIDE_PANEL_WIDTH
# COMBAT_PANEL_HEIGHT = round(SCREEN_HEIGHT // 3)

# OBJECTS PANEL
# OBJECT_PANEL_WIDTH = SCREEN_WIDTH // 5
# OBJECT_PANEL_HEIGHT = round(SCREEN_HEIGHT // 3)

# Message panels
MSG_PANEL1_WIDTH = BOTTOM_PANEL_WIDTH // 2 - 4
MSG_PANEL2_WIDTH = BOTTOM_PANEL_WIDTH // 2 + 4
MSG_PANEL1_X = 0
MSG_PANEL2_X = MSG_PANEL1_WIDTH

# Message display
MSG_X = 1
MSG_HEIGHT = BOTTOM_PANELS_HEIGHT - 3

# POPUP WINDOWS
INVENTORY_WIDTH = 30